org: winso
app: star-wars-api
service: star-wars-api
frameworkVersion: '3'

custom:
  serverless-offline:
    noPrependStageInUrl: true
    useChildProcesses: false
  tableName: 'people-table-${sls:stage}'
  esbuild:
    bundle: true  # Habilita el empaquetado
    minify: true   # Minifica el código (opcional)
    sourcemap: true  # Genera sourcemaps (opcional)
    target: node18  # Versión de Node.js objetivo
    exclude: []
    watch:
      pattern: 'src/**/*.ts'
      ignore: '.serverless/**/*'

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ PeopleTable, Arn ]
  environment:
    PEOPLE_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'
  # create-people:
  #   handler: src/index.handler
  #   events:
  #     - http:
  #         path: people
  #         method: POST
  # read-people:
  #   handler: src/index.handler
  #   events:
  #     - http:
  #         path: people/{peopleId}
  #         method: GET
  # read-all-people:
  #   handler: src/index.handler
  #   events:
  #     - http:
  #         path: people
  #         method: GET
  # delete-people:
  #   handler: src/index.handler
  #   events:
  #     - http:
  #         path: people/{peopleId}
  #         method: DELETE

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: peopleId
            AttributeType: S
        KeySchema:
          - AttributeName: peopleId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb
