org: winso
app: star-wars-api
service: star-wars-api
frameworkVersion: '3'

custom:
  serverless-offline:
    noPrependStageInUrl: true
    useChildProcesses: false
  tableName: 'people-table-${sls:stage}'
  esbuild:
    minify: true
    external:
      - aws-sdk
    watch:
      pattern: 'src/**/*.ts'
      ignore: '.serverless/**/*'
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ PeopleTable, Arn ]
  environment:
    PEOPLE_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: src/index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: peopleId
            AttributeType: S
        KeySchema:
          - AttributeName: peopleId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dynamodb
